CREATE TABLE "car" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "brand" varchar NOT NULL,
  "model" varchar NOT NULL,
  "plate" varchar NOT NULL,
  "image" text,
  "type" varchar NOT NULL,
  "transmission" varchar NOT NULL,
  "year" integer NOT NULL,
  "capacity" integer NOT NULL,
  "rentPerDay" integer NOT NULL,
  "available" bool NOT NULL,
  "availableAt" timestamp NOT NULL,
  "deletedAt" timestamp,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "customer" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "address" varchar NOT NULL,
  "phoneNumber" bigint NOT NULL,
  "deletedAt" timestamp,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

CREATE TABLE "reservation" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "car_id" bigint,
  "customer_id" bigint,
  "reservationDate" timestamp NOT NULL,
  "returnDate" timestamp NOT NULL,
  "deletedAt" timestamp,
  "createdAt" timestamp DEFAULT (now()),
  "updatedAt" timestamp DEFAULT (now())
);

ALTER TABLE "reservation" ADD FOREIGN KEY ("car_id") REFERENCES "car" ("id");

ALTER TABLE "reservation" ADD FOREIGN KEY ("customer_id") REFERENCES "customer" ("id");
